exports.GET_HEARTBEAT = 'GET_HEARTBEAT';

exports.NEW_USER_REGISTER = 'NEW_USER_REGISTER';
exports.NEW_ACCESS_TOKEN = 'NEW_ACCESS_TOKEN';

exports.BILL_COMPLETED = 'BILL_COMPLETED';
exports.BILL_CREATED = 'BILL_CREATED'

exports.SEARCH_PRODUCTS_V2 = 'SEARCH_PRODUCTS_V2'

exports.SEARCH_HISTORY_PRODUCTS = 'SEARCH_HISTORY_PRODUCT'
